### ISSUE TITLE
Variable product # based on environment?

### ISSUE THREAD

**Issue by silverfox1948** [jacopotarantino/ng-optimizely#11]
Hi, 
This looks quite useful. We are new to Angular, and using Node for our back end (also new for us).

We have different project #'s base upon the environment in which the Angular app is running: "dev", "test", "stage" or "prod".
I can figure out how to change the product id based on the env value. What I'm struggling with is how to get the value of the environment from the Angular app itself. There is a config file for the entire application, but the other angular functions are getting the config values doing an $http.get to the server. I'm assuming I need to do this at an earlier stage, and then set the project id at startup.

Any suggestions (or examples) of how to do this at the client side instead of getting it from the server side?

**Comment by jacopotarantino** [comment]
Hey, sorry for the slow reply. Ideally, I'd be working off of your codebase to make a suggestion but here we go:
https://github.com/juanpablob/angular-environment is a pretty swanky solution. I used one before that interpolated variables directly into processed files but since I can't seem to find that anymore, why don't you check out https://github.com/ajwhite/gulp-ng-config which does basically the same thing. Let me know if that helps!

**Comment by jacopotarantino** [comment]
Closing for now as this isn't a bug in the software but feel free to continue commenting.
