### ISSUE TITLE
Add Examples

### ISSUE THREAD

**Issue by scottgl** [jacopotarantino/ng-optimizely#3]
Hey Jack - Thanks for creating this. 

To get more traction I'd recommend adding some pseudo real world examples of how to implement this. 

Personally, I'm using this library https://github.com/mattvv/angular-optimizely, as getting up and running with it was really straightforward.

He outlines how to quickly get up and running in the Usage section of the README.

I'd love to try yours, I'd just prefer to see a real world example of what I'm even supposed to do.

**Comment by jacopotarantino** [comment]
Hey, thanks for the note. While mattvv's project provides directives, this one does not. Unless I missed something, I believe all of the functionality is documented in the Readme file. The only thing this project does is load the optimizely script onto the page and provide a promise that resolves when it finishes loading. It allows you to keep all of the functionality in your application within the world of Angular so you don't have to have a separate `<script>` tag for optimizely.

If that doesn't make sense or if you could point out something specific that I missed, I'd be happy to make an update but otherwise, I think everything is covered.
